### ISSUE TITLE
ANDROIDX_VERSION issue

### ISSUE THREAD

**Issue by Make-It-Racing** [rmptxf/nrf52_ble_tester_project#1]
This is amazing, thank you so much for the video and the code.
I was straggling with one thing and I think it can save lots of time to others if you mention this.
The pacakge.json file has this code:

      "cordova.plugins.diagnostic": {
        "ANDROIDX_VERSION": "1.+"
      }

The "+" means it will use the latest version available, in my case that was a newer version than the one you used when recording the video, this created lots of issues and errors (the newer versions have other dependencies).
To fix this the  code should be replaced with:

      "cordova.plugins.diagnostic": {
        "ANDROIDX_VERSION": "1.0.0"
      }

**Comment by rmptxf** [comment]
You're very welcome, and glad you found it helpful!

Thanks a lot for mentioning this issue @PlayRobotics.

I have updated it.

**Comment by playrobotics-alex** [comment]
Thanks again, 
another small questions, can you please tell me where I can edit the "intro" screen shown in the screenshot:
![image](https://user-images.githubusercontent.com/60300961/154932923-9bf6b746-7cda-40d0-b04e-628f4526cb17.png)
